import Head from "next/head";
import { Navbar, Footer } from "components";

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Karly Hoffman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}

export default Layout;
